apiVersion: loki.grafana.com/v1
kind: LokiStack
metadata:
  name: logging-loki
  namespace: openshift-logging
spec:
  managementState: Managed
  rules:
    enabled: true
    namespaceSelector:
      matchLabels:
        openshift.io/log-alerting: 'true'
    selector:
      matchLabels:
        openshift.io/log-alerting: 'true'
  size: 1x.extra-small
  storage:
    schemas:
    - version: v13
      effectiveDate: "2024-03-01"
    secret:
      name: test-bucket
      type: s3
  storageClassName: gp2-csi
  tenants:
    mode: openshift-logging